"""feat: add credits field to course table

Revision ID: 230fb628282b
Revises: 2a7d6f3e415f
Create Date: 2026-05-30 18:34:57.045012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230fb628282b'
down_revision: Union[str, Sequence[str], None] = '2a7d6f3e415f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('credits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'credits')
    # ### end Alembic commands ###
