"""feat: add level, num_hours, website, playlist columns to Course table

Revision ID: 2a7d6f3e415f
Revises: 9244277cc931
Create Date: 2026-05-30 18:20:15.906407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7d6f3e415f'
down_revision: Union[str, Sequence[str], None] = '9244277cc931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('level', sa.String(length=20), nullable=True))
    op.add_column('course', sa.Column('num_hours', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('course', sa.Column('playlist', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'playlist')
    op.drop_column('course', 'website')
    op.drop_column('course', 'num_hours')
    op.drop_column('course', 'level')
    # ### end Alembic commands ###
