"""feat: add num_weeks to course model for performance

Revision ID: 63efabeac23c
Revises: ba90f0af7a08
Create Date: 2026-06-03 00:03:58.657463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63efabeac23c'
down_revision: Union[str, Sequence[str], None] = 'ba90f0af7a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('num_weeks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'num_weeks')
    # ### end Alembic commands ###
