"""feat: add timestamp to student lecture model

Revision ID: 91b071c1ae9e
Revises: cabf4163895b
Create Date: 2026-05-22 01:02:43.745801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b071c1ae9e'
down_revision: Union[str, Sequence[str], None] = 'cabf4163895b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_lecture', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_lecture', 'timestamp')
    # ### end Alembic commands ###
