"""feat: add dependency model

Revision ID: 9244277cc931
Revises: 91b071c1ae9e
Create Date: 2026-05-24 03:01:13.809505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9244277cc931'
down_revision: Union[str, Sequence[str], None] = '91b071c1ae9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependency', sa.Column('from_course_id', sa.UUID(), nullable=False))
    op.add_column('dependency', sa.Column('to_course_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'dependency', 'course', ['to_course_id'], ['id'])
    op.create_foreign_key(None, 'dependency', 'course', ['from_course_id'], ['id'])
    op.drop_column('dependency', 'name')
    op.drop_column('dependency', 'description')
    op.drop_column('dependency', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependency', sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('dependency', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('dependency', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dependency', type_='foreignkey')
    op.drop_constraint(None, 'dependency', type_='foreignkey')
    op.drop_column('dependency', 'to_course_id')
    op.drop_column('dependency', 'from_course_id')
    # ### end Alembic commands ###
