"""feat: set on-delete=cascade for all models

Revision ID: ba90f0af7a08
Revises: 9f59bd3eed9a
Create Date: 2026-05-31 17:31:17.377549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba90f0af7a08'
down_revision: Union[str, Sequence[str], None] = '9f59bd3eed9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('dependency_from_course_id_fkey'), 'dependency', type_='foreignkey')
    op.drop_constraint(op.f('dependency_to_course_id_fkey'), 'dependency', type_='foreignkey')
    op.create_foreign_key(None, 'dependency', 'course', ['from_course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dependency', 'course', ['to_course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('lecture_week_id_fkey'), 'lecture', type_='foreignkey')
    op.create_foreign_key(None, 'lecture', 'week', ['week_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('student_user_id_fkey'), 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('student_lecture_lecture_id_fkey'), 'student_lecture', type_='foreignkey')
    op.drop_constraint(op.f('student_lecture_student_id_fkey'), 'student_lecture', type_='foreignkey')
    op.create_foreign_key(None, 'student_lecture', 'lecture', ['lecture_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'student_lecture', 'student', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('week_course_id_fkey'), 'week', type_='foreignkey')
    op.create_foreign_key(None, 'week', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'week', type_='foreignkey')
    op.create_foreign_key(op.f('week_course_id_fkey'), 'week', 'course', ['course_id'], ['id'])
    op.drop_constraint(None, 'student_lecture', type_='foreignkey')
    op.drop_constraint(None, 'student_lecture', type_='foreignkey')
    op.create_foreign_key(op.f('student_lecture_student_id_fkey'), 'student_lecture', 'student', ['student_id'], ['id'])
    op.create_foreign_key(op.f('student_lecture_lecture_id_fkey'), 'student_lecture', 'lecture', ['lecture_id'], ['id'])
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key(op.f('student_user_id_fkey'), 'student', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'lecture', type_='foreignkey')
    op.create_foreign_key(op.f('lecture_week_id_fkey'), 'lecture', 'week', ['week_id'], ['id'])
    op.drop_constraint(None, 'dependency', type_='foreignkey')
    op.drop_constraint(None, 'dependency', type_='foreignkey')
    op.create_foreign_key(op.f('dependency_to_course_id_fkey'), 'dependency', 'course', ['to_course_id'], ['id'])
    op.create_foreign_key(op.f('dependency_from_course_id_fkey'), 'dependency', 'course', ['from_course_id'], ['id'])
    # ### end Alembic commands ###
